version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/html/static-website-example/
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/stop_apache.sh
      runas: root
  AfterInstall:
    - location: scripts/start_apache.sh
      timeout: 180
      runas: root
